// premium/electron/knowledge/NegotiationEngine.ts
//
// Open-source local re-implementation. Part of the AGPL-3.0 Natively fork.
//
// Builds an ahead-of-time (AOT) salary-negotiation script from the user's resume
// and target JD. The script is generated by the injected quality-first LLM
// function and cached by the orchestrator. Treated opaquely by the renderer.

import type { StructuredResume, StructuredJD } from './types';

export type GenerateContentFn = (
  contents: Array<{ text: string }> | string,
) => Promise<string>;

export interface NegotiationScript {
  summary: string;
  anchorRange?: { low: number | null; high: number | null; currency: string };
  talkingPoints: string[];
  leverage: string[];
  scripts: { situation: string; say: string }[];
  generatedAt: number;
}

function tryParseJSON<T>(text: string): T | null {
  if (!text) return null;
  try {
    const match = text.match(/\{[\s\S]*\}/);
    return JSON.parse(match ? match[0] : text) as T;
  } catch {
    return null;
  }
}

export class NegotiationEngine {
  constructor(private generateFn: GenerateContentFn | null = null) {}

  setGenerateContentFn(fn: GenerateContentFn): void {
    this.generateFn = fn;
  }

  async generateScript(
    resume: StructuredResume | null,
    jd: StructuredJD | null,
  ): Promise<NegotiationScript | null> {
    if (!this.generateFn) return null;

    const name = resume?.identity?.name ?? 'the candidate';
    const role = jd?.title ?? resume?.experience?.[0]?.role ?? 'the role';
    const company = jd?.company ?? 'the company';
    const compHint = jd?.compensation_hint ?? '';

    const prompt = [
      'You are an expert tech-compensation negotiation coach. Produce a concise,',
      'practical negotiation plan for the candidate below. Return STRICT JSON with',
      'this shape:',
      '{"summary": string, "anchorRange": {"low": number|null, "high": number|null, "currency": "$"},',
      '"talkingPoints": string[], "leverage": string[],',
      '"scripts": [{"situation": string, "say": string}]}',
      '',
      `Candidate: ${name}`,
      `Target role: ${role} at ${company}`,
      compHint ? `Stated compensation hint: ${compHint}` : '',
      resume ? `Key skills: ${JSON.stringify(resume.skills)}` : '',
      'Ground all numbers in typical market ranges for the role and seniority.',
      'Keep talkingPoints and leverage to 3–5 items each, scripts to 3–4 entries.',
    ].filter(Boolean).join('\n');

    let raw = '';
    try {
      raw = await this.generateFn([{ text: prompt }]);
    } catch {
      return null;
    }
    const parsed = tryParseJSON<Partial<NegotiationScript>>(raw);
    if (!parsed) {
      // Degrade gracefully to a text-only script rather than failing outright.
      return {
        summary: raw.slice(0, 1200) || 'Negotiation guidance unavailable.',
        talkingPoints: [],
        leverage: [],
        scripts: [],
        generatedAt: Date.now(),
      };
    }
    return {
      summary: parsed.summary ?? '',
      anchorRange: parsed.anchorRange ?? { low: null, high: null, currency: '$' },
      talkingPoints: parsed.talkingPoints ?? [],
      leverage: parsed.leverage ?? [],
      scripts: parsed.scripts ?? [],
      generatedAt: Date.now(),
    };
  }
}
